# Generated by Django 4.1.7 on 2023-03-23 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=35)),
                ('intercessors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
